/* 
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AccountMaster {
  #[serde(rename = "officialTitle")]
  official_title: Option<String>,
  #[serde(rename = "title")]
  title: Option<String>
}

impl AccountMaster {
  pub fn new() -> AccountMaster {
    AccountMaster {
      official_title: None,
      title: None
    }
  }

  pub fn set_official_title(&mut self, official_title: String) {
    self.official_title = Some(official_title);
  }

  pub fn with_official_title(mut self, official_title: String) -> AccountMaster {
    self.official_title = Some(official_title);
    self
  }

  pub fn official_title(&self) -> Option<&String> {
    self.official_title.as_ref()
  }

  pub fn reset_official_title(&mut self) {
    self.official_title = None;
  }

  pub fn set_title(&mut self, title: String) {
    self.title = Some(title);
  }

  pub fn with_title(mut self, title: String) -> AccountMaster {
    self.title = Some(title);
    self
  }

  pub fn title(&self) -> Option<&String> {
    self.title.as_ref()
  }

  pub fn reset_title(&mut self) {
    self.title = None;
  }

}



