/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Body11 {
  #[serde(rename = "conids")]
  conids: Option<Vec<i32>>
}

impl Body11 {
  pub fn new() -> Body11 {
    Body11 {
      conids: None
    }
  }

  pub fn set_conids(&mut self, conids: Vec<i32>) {
    self.conids = Some(conids);
  }

  pub fn with_conids(mut self, conids: Vec<i32>) -> Body11 {
    self.conids = Some(conids);
    self
  }

  pub fn conids(&self) -> Option<&Vec<i32>> {
    self.conids.as_ref()
  }

  pub fn reset_conids(&mut self) {
    self.conids = None;
  }

}



