/* 
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Body3 {
  #[serde(rename = "acctIds")]
  acct_ids: Option<Vec<String>>
}

impl Body3 {
  pub fn new() -> Body3 {
    Body3 {
      acct_ids: None
    }
  }

  pub fn set_acct_ids(&mut self, acct_ids: Vec<String>) {
    self.acct_ids = Some(acct_ids);
  }

  pub fn with_acct_ids(mut self, acct_ids: Vec<String>) -> Body3 {
    self.acct_ids = Some(acct_ids);
    self
  }

  pub fn acct_ids(&self) -> Option<&Vec<String>> {
    self.acct_ids.as_ref()
  }

  pub fn reset_acct_ids(&mut self) {
    self.acct_ids = None;
  }

}



