/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Body3 {
  #[serde(rename = "filters")]
  filters: Option<Vec<String>>
}

impl Body3 {
  pub fn new() -> Body3 {
    Body3 {
      filters: None
    }
  }

  pub fn set_filters(&mut self, filters: Vec<String>) {
    self.filters = Some(filters);
  }

  pub fn with_filters(mut self, filters: Vec<String>) -> Body3 {
    self.filters = Some(filters);
    self
  }

  pub fn filters(&self) -> Option<&Vec<String>> {
    self.filters.as_ref()
  }

  pub fn reset_filters(&mut self) {
    self.filters = None;
  }

}



