/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2001 {
  /// Challenge in hex format
  #[serde(rename = "challenge")]
  challenge: Option<Value>
}

impl InlineResponse2001 {
  pub fn new() -> InlineResponse2001 {
    InlineResponse2001 {
      challenge: None
    }
  }

  pub fn set_challenge(&mut self, challenge: Value) {
    self.challenge = Some(challenge);
  }

  pub fn with_challenge(mut self, challenge: Value) -> InlineResponse2001 {
    self.challenge = Some(challenge);
    self
  }

  pub fn challenge(&self) -> Option<&Value> {
    self.challenge.as_ref()
  }

  pub fn reset_challenge(&mut self) {
    self.challenge = None;
  }

}



