/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse200 {
  /// List of tradeable or Sub Accounts
  #[serde(rename = "acctList")]
  acct_list: Option<Vec<::models::InlineResponse200AcctList>>,
  /// The primary or parent account.
  #[serde(rename = "mainAcct")]
  main_acct: Option<String>
}

impl InlineResponse200 {
  pub fn new() -> InlineResponse200 {
    InlineResponse200 {
      acct_list: None,
      main_acct: None
    }
  }

  pub fn set_acct_list(&mut self, acct_list: Vec<::models::InlineResponse200AcctList>) {
    self.acct_list = Some(acct_list);
  }

  pub fn with_acct_list(mut self, acct_list: Vec<::models::InlineResponse200AcctList>) -> InlineResponse200 {
    self.acct_list = Some(acct_list);
    self
  }

  pub fn acct_list(&self) -> Option<&Vec<::models::InlineResponse200AcctList>> {
    self.acct_list.as_ref()
  }

  pub fn reset_acct_list(&mut self) {
    self.acct_list = None;
  }

  pub fn set_main_acct(&mut self, main_acct: String) {
    self.main_acct = Some(main_acct);
  }

  pub fn with_main_acct(mut self, main_acct: String) -> InlineResponse200 {
    self.main_acct = Some(main_acct);
    self
  }

  pub fn main_acct(&self) -> Option<&String> {
    self.main_acct.as_ref()
  }

  pub fn reset_main_acct(&mut self) {
    self.main_acct = None;
  }

}



