/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20010 {
  #[serde(rename = "applicantId")]
  applicant_id: Option<f32>,
  #[serde(rename = "entities")]
  entities: Option<Vec<::models::IbcustentityinfoEntities>>
}

impl InlineResponse20010 {
  pub fn new() -> InlineResponse20010 {
    InlineResponse20010 {
      applicant_id: None,
      entities: None
    }
  }

  pub fn set_applicant_id(&mut self, applicant_id: f32) {
    self.applicant_id = Some(applicant_id);
  }

  pub fn with_applicant_id(mut self, applicant_id: f32) -> InlineResponse20010 {
    self.applicant_id = Some(applicant_id);
    self
  }

  pub fn applicant_id(&self) -> Option<&f32> {
    self.applicant_id.as_ref()
  }

  pub fn reset_applicant_id(&mut self) {
    self.applicant_id = None;
  }

  pub fn set_entities(&mut self, entities: Vec<::models::IbcustentityinfoEntities>) {
    self.entities = Some(entities);
  }

  pub fn with_entities(mut self, entities: Vec<::models::IbcustentityinfoEntities>) -> InlineResponse20010 {
    self.entities = Some(entities);
    self
  }

  pub fn entities(&self) -> Option<&Vec<::models::IbcustentityinfoEntities>> {
    self.entities.as_ref()
  }

  pub fn reset_entities(&mut self) {
    self.entities = None;
  }

}



