/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20016 {
  #[serde(rename = "acctId")]
  acct_id: Option<Value>
}

impl InlineResponse20016 {
  pub fn new() -> InlineResponse20016 {
    InlineResponse20016 {
      acct_id: None
    }
  }

  pub fn set_acct_id(&mut self, acct_id: Value) {
    self.acct_id = Some(acct_id);
  }

  pub fn with_acct_id(mut self, acct_id: Value) -> InlineResponse20016 {
    self.acct_id = Some(acct_id);
    self
  }

  pub fn acct_id(&self) -> Option<&Value> {
    self.acct_id.as_ref()
  }

  pub fn reset_acct_id(&mut self) {
    self.acct_id = None;
  }

}



