/* 
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2001 {
  #[serde(rename = "set")]
  set: Option<bool>,
  #[serde(rename = "acctId")]
  acct_id: Option<String>
}

impl InlineResponse2001 {
  pub fn new() -> InlineResponse2001 {
    InlineResponse2001 {
      set: None,
      acct_id: None
    }
  }

  pub fn set_set(&mut self, set: bool) {
    self.set = Some(set);
  }

  pub fn with_set(mut self, set: bool) -> InlineResponse2001 {
    self.set = Some(set);
    self
  }

  pub fn set(&self) -> Option<&bool> {
    self.set.as_ref()
  }

  pub fn reset_set(&mut self) {
    self.set = None;
  }

  pub fn set_acct_id(&mut self, acct_id: String) {
    self.acct_id = Some(acct_id);
  }

  pub fn with_acct_id(mut self, acct_id: String) -> InlineResponse2001 {
    self.acct_id = Some(acct_id);
    self
  }

  pub fn acct_id(&self) -> Option<&String> {
    self.acct_id.as_ref()
  }

  pub fn reset_acct_id(&mut self) {
    self.acct_id = None;
  }

}



