/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2007 {
  /// disclaimer message
  #[serde(rename = "DT")]
  DT: Option<String>,
  /// fyi code
  #[serde(rename = "FC")]
  FC: Option<String>
}

impl InlineResponse2007 {
  pub fn new() -> InlineResponse2007 {
    InlineResponse2007 {
      DT: None,
      FC: None
    }
  }

  pub fn set_DT(&mut self, DT: String) {
    self.DT = Some(DT);
  }

  pub fn with_DT(mut self, DT: String) -> InlineResponse2007 {
    self.DT = Some(DT);
    self
  }

  pub fn DT(&self) -> Option<&String> {
    self.DT.as_ref()
  }

  pub fn reset_DT(&mut self) {
    self.DT = None;
  }

  pub fn set_FC(&mut self, FC: String) {
    self.FC = Some(FC);
  }

  pub fn with_FC(mut self, FC: String) -> InlineResponse2007 {
    self.FC = Some(FC);
    self
  }

  pub fn FC(&self) -> Option<&String> {
    self.FC.as_ref()
  }

  pub fn reset_FC(&mut self) {
    self.FC = None;
  }

}



