/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2003 {
  #[serde(rename = "orders")]
  orders: Option<Vec<::models::OrderData>>
}

impl InlineResponse2003 {
  pub fn new() -> InlineResponse2003 {
    InlineResponse2003 {
      orders: None
    }
  }

  pub fn set_orders(&mut self, orders: Vec<::models::OrderData>) {
    self.orders = Some(orders);
  }

  pub fn with_orders(mut self, orders: Vec<::models::OrderData>) -> InlineResponse2003 {
    self.orders = Some(orders);
    self
  }

  pub fn orders(&self) -> Option<&Vec<::models::OrderData>> {
    self.orders.as_ref()
  }

  pub fn reset_orders(&mut self) {
    self.orders = None;
  }

}



