/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20011 {
  #[serde(rename = "acctId")]
  acct_id: Option<String>,
  #[serde(rename = "set")]
  set: Option<bool>
}

impl InlineResponse20011 {
  pub fn new() -> InlineResponse20011 {
    InlineResponse20011 {
      acct_id: None,
      set: None
    }
  }

  pub fn set_acct_id(&mut self, acct_id: String) {
    self.acct_id = Some(acct_id);
  }

  pub fn with_acct_id(mut self, acct_id: String) -> InlineResponse20011 {
    self.acct_id = Some(acct_id);
    self
  }

  pub fn acct_id(&self) -> Option<&String> {
    self.acct_id.as_ref()
  }

  pub fn reset_acct_id(&mut self) {
    self.acct_id = None;
  }

  pub fn set_set(&mut self, set: bool) {
    self.set = Some(set);
  }

  pub fn with_set(mut self, set: bool) -> InlineResponse20011 {
    self.set = Some(set);
    self
  }

  pub fn set(&self) -> Option<&bool> {
    self.set.as_ref()
  }

  pub fn reset_set(&mut self) {
    self.set = None;
  }

}



