/* 
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2004 {
  /// unread number
  #[serde(rename = "BN")]
  BN: Option<i32>
}

impl InlineResponse2004 {
  pub fn new() -> InlineResponse2004 {
    InlineResponse2004 {
      BN: None
    }
  }

  pub fn set_BN(&mut self, BN: i32) {
    self.BN = Some(BN);
  }

  pub fn with_BN(mut self, BN: i32) -> InlineResponse2004 {
    self.BN = Some(BN);
    self
  }

  pub fn BN(&self) -> Option<&i32> {
    self.BN.as_ref()
  }

  pub fn reset_BN(&mut self) {
    self.BN = None;
  }

}



