/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse20030 {
  #[serde(rename = "call")]
  call: Option<Vec<String>>,
  #[serde(rename = "put")]
  put: Option<Vec<String>>
}

impl InlineResponse20030 {
  pub fn new() -> InlineResponse20030 {
    InlineResponse20030 {
      call: None,
      put: None
    }
  }

  pub fn set_call(&mut self, call: Vec<String>) {
    self.call = Some(call);
  }

  pub fn with_call(mut self, call: Vec<String>) -> InlineResponse20030 {
    self.call = Some(call);
    self
  }

  pub fn call(&self) -> Option<&Vec<String>> {
    self.call.as_ref()
  }

  pub fn reset_call(&mut self) {
    self.call = None;
  }

  pub fn set_put(&mut self, put: Vec<String>) {
    self.put = Some(put);
  }

  pub fn with_put(mut self, put: Vec<String>) -> InlineResponse20030 {
    self.put = Some(put);
    self
  }

  pub fn put(&self) -> Option<&Vec<String>> {
    self.put.as_ref()
  }

  pub fn reset_put(&mut self) {
    self.put = None;
  }

}



