/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// PerformanceNav : Net asset value data for the account or consolidated accounts. NAV data is not applicable to benchmarks.

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct PerformanceNav {
  #[serde(rename = "data")]
  data: Option<Vec<::models::PerformanceCpsData>>,
  /// array of dates, the length should be same as the length of returns inside data.
  #[serde(rename = "dates")]
  dates: Option<Vec<String>>,
  /// D means Day
  #[serde(rename = "freq")]
  freq: Option<String>
}

impl PerformanceNav {
  /// Net asset value data for the account or consolidated accounts. NAV data is not applicable to benchmarks.
  pub fn new() -> PerformanceNav {
    PerformanceNav {
      data: None,
      dates: None,
      freq: None
    }
  }

  pub fn set_data(&mut self, data: Vec<::models::PerformanceCpsData>) {
    self.data = Some(data);
  }

  pub fn with_data(mut self, data: Vec<::models::PerformanceCpsData>) -> PerformanceNav {
    self.data = Some(data);
    self
  }

  pub fn data(&self) -> Option<&Vec<::models::PerformanceCpsData>> {
    self.data.as_ref()
  }

  pub fn reset_data(&mut self) {
    self.data = None;
  }

  pub fn set_dates(&mut self, dates: Vec<String>) {
    self.dates = Some(dates);
  }

  pub fn with_dates(mut self, dates: Vec<String>) -> PerformanceNav {
    self.dates = Some(dates);
    self
  }

  pub fn dates(&self) -> Option<&Vec<String>> {
    self.dates.as_ref()
  }

  pub fn reset_dates(&mut self) {
    self.dates = None;
  }

  pub fn set_freq(&mut self, freq: String) {
    self.freq = Some(freq);
  }

  pub fn with_freq(mut self, freq: String) -> PerformanceNav {
    self.freq = Some(freq);
    self
  }

  pub fn freq(&self) -> Option<&String> {
    self.freq.as_ref()
  }

  pub fn reset_freq(&mut self) {
    self.freq = None;
  }

}



