/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ScannerparamsLocationTreeLocation {
  #[serde(rename = "displayName")]
  display_name: Option<String>,
  #[serde(rename = "instruments")]
  instruments: Option<String>,
  #[serde(rename = "locationCode")]
  location_code: Option<String>,
  #[serde(rename = "routeExchange")]
  route_exchange: Option<String>
}

impl ScannerparamsLocationTreeLocation {
  pub fn new() -> ScannerparamsLocationTreeLocation {
    ScannerparamsLocationTreeLocation {
      display_name: None,
      instruments: None,
      location_code: None,
      route_exchange: None
    }
  }

  pub fn set_display_name(&mut self, display_name: String) {
    self.display_name = Some(display_name);
  }

  pub fn with_display_name(mut self, display_name: String) -> ScannerparamsLocationTreeLocation {
    self.display_name = Some(display_name);
    self
  }

  pub fn display_name(&self) -> Option<&String> {
    self.display_name.as_ref()
  }

  pub fn reset_display_name(&mut self) {
    self.display_name = None;
  }

  pub fn set_instruments(&mut self, instruments: String) {
    self.instruments = Some(instruments);
  }

  pub fn with_instruments(mut self, instruments: String) -> ScannerparamsLocationTreeLocation {
    self.instruments = Some(instruments);
    self
  }

  pub fn instruments(&self) -> Option<&String> {
    self.instruments.as_ref()
  }

  pub fn reset_instruments(&mut self) {
    self.instruments = None;
  }

  pub fn set_location_code(&mut self, location_code: String) {
    self.location_code = Some(location_code);
  }

  pub fn with_location_code(mut self, location_code: String) -> ScannerparamsLocationTreeLocation {
    self.location_code = Some(location_code);
    self
  }

  pub fn location_code(&self) -> Option<&String> {
    self.location_code.as_ref()
  }

  pub fn reset_location_code(&mut self) {
    self.location_code = None;
  }

  pub fn set_route_exchange(&mut self, route_exchange: String) {
    self.route_exchange = Some(route_exchange);
  }

  pub fn with_route_exchange(mut self, route_exchange: String) -> ScannerparamsLocationTreeLocation {
    self.route_exchange = Some(route_exchange);
    self
  }

  pub fn route_exchange(&self) -> Option<&String> {
    self.route_exchange.as_ref()
  }

  pub fn reset_route_exchange(&mut self) {
    self.route_exchange = None;
  }

}



