/* 
 * Client Portal Web API
 *
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ScannerresultContracts : Contains list of contracts matching the scanner query

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ScannerresultContracts {
  #[serde(rename = "Contract")]
  contract: Option<Vec<::models::ScannerresultContractsContract>>
}

impl ScannerresultContracts {
  /// Contains list of contracts matching the scanner query
  pub fn new() -> ScannerresultContracts {
    ScannerresultContracts {
      contract: None
    }
  }

  pub fn set_contract(&mut self, contract: Vec<::models::ScannerresultContractsContract>) {
    self.contract = Some(contract);
  }

  pub fn with_contract(mut self, contract: Vec<::models::ScannerresultContractsContract>) -> ScannerresultContracts {
    self.contract = Some(contract);
    self
  }

  pub fn contract(&self) -> Option<&Vec<::models::ScannerresultContractsContract>> {
    self.contract.as_ref()
  }

  pub fn reset_contract(&mut self) {
    self.contract = None;
  }

}



